// const variable_ = {'ALLUSERSPROFILE': 'C:\\ProgramData',
//  'APPDATA': 'C:\\Users\\user2\\AppData\\Roaming',
//   'BR_TG_PATH': 'C:\\BrAutomation\\AsTools\\Technology Guarding',
//    'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_8280_KCZZWTRXQXJFPTOZ',
//     'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 
//     'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 
//     'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 
//     'COMPUTERNAME': 'SYSTEM2', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',
//      'CUDA_PATH': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1',
//       'CUDA_PATH_V10_0': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0',
//        'CUDA_PATH_V10_1': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1',
//         'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 
//         'ENV_PROMPT': '(schnell_server) ',
//          'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 
//          'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
//           'HOMEDRIVE': 'Z:', 'HOMEPATH': '\\',
//            'HOMESHARE': '\\\\MAIN_SERVER.SCHNELLPACK.com\\USERS\\USER2',
//             'LOCALAPPDATA': 'C:\\Users\\user2\\AppData\\Local',
//              'LOGONSERVER': '\\\\MAIN_SERVER',
//               'NUMBER_OF_PROCESSORS': '4', 
//              'NVCUDASAMPLES10_0_ROOT': 'C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v10.0',
//               'NVCUDASAMPLES10_1_ROOT': 'C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v10.1', 
//               'NVCUDASAMPLES_ROOT': 'C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v10.1', 
//               'NVTOOLSEXT_PATH': 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\', 
//               'ONEDRIVE': 'C:\\Users\\user2\\OneDrive',
//                'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 
// 'OS': 'Windows_NT', 
// 'PATH': 'C:\\Users\\user2\\.virtualenvs\\schnell_server-xFwyBJvi\\Scripts;C:\\Program Files\\Python37\\Scripts\\;C:\\Program Files\\Python37\\;C:\\TwinCAT\\Common64;C:\\TwinCAT\\Common32;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\libnvvp;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2019.1\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PostgreSQL\\12\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\Users\\user2\\AppData\\Roaming\\npm;C:\\Users\\user2\\AppData\\Local\\Programs\\Python\\Python37\\Scripts\\;C:\\Users\\user2\\AppData\\Local\\Programs\\Python\\Python37\\;C:\\Users\\user2\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\user2\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\GitHub CLI\\',
//  'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 
//  'PROCESSOR_ARCHITECTURE': 'AMD64', 
//  'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 11, GenuineIntel',
//   'PROCESSOR_LEVEL': '6', 
//   'PROCESSOR_REVISION': '9e0b',
//    'PROGRAMDATA': 'C:\\ProgramData', 
//    'PROGRAMFILES': 'C:\\Program Files',
//     'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
//      'PROGRAMW6432': 'C:\\Program Files',
//       'PROMPT': '(schnell_server) $P$G', 
//      'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules', 
//      'PUBLIC': 'C:\\Users\\Public', 
//      'SESSIONNAME': 'Console',
//       'SYSTEMDRIVE': 'C:',
//        'SYSTEMROOT': 'C:\\Windows',
//       'TEMP': 'C:\\Users\\user2\\AppData\\Local\\Temp',
//        'TMP': 'C:\\Users\\user2\\AppData\\Local\\Temp', 
//      'TWINCAT3DIR': 'C:\\TwinCAT\\3.1\\',
//       'TWINCATSDK': 'C:\\TwinCAT\\3.1\\SDK\\',
//        'USERDNSDOMAIN': 'SCHNELLPACK.COM', 
//        'USERDOMAIN': 'SCHNELLPACK', 
//        'USERDOMAIN_ROAMINGPROFILE': 'SCHNELLPACK', 
//        'USERNAME': 'user2', 
//        'USERPROFILE': 'C:\\Users\\user2',
//         'VIRTUAL_ENV': 'C:\\Users\\user2\\.virtualenvs\\schnell_server-xFwyBJvi',
//          'VS150COMCOMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\',
//           'VS160COMCOMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\', 
//           'WINDIR': 'C:\\Windows', 'TERM_PROGRAM': 'vscode',
//            'TERM_PROGRAM_VERSION': '1.60.1', 'LANG': 'en_US.UTF-8', 
//           'COLORTERM': 'truecolor', 'VSCODE_GIT_IPC_HANDLE': '\\\\.\\pipe\\vscode-git-3fb38c2a6b-sock', 
//           'GIT_ASKPASS': 'c:\\Program Files\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
//            'VSCODE_GIT_ASKPASS_NODE': 'C:\\Program Files\\Microsoft VS Code\\Code.exe', 
//            'VSCODE_GIT_ASKPASS_MAIN': 'c:\\Program Files\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
//             '_OLD_VIRTUAL_PATH': 'C:\\Program Files\\Python37\\Scripts\\;C:\\Program Files\\Python37\\;C:\\TwinCAT\\Common64;C:\\TwinCAT\\Common32;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\libnvvp;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\libnvvp;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2019.1\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PostgreSQL\\12\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\Users\\user2\\AppData\\Roaming\\npm;C:\\Users\\user2\\AppData\\Local\\Programs\\Python\\Python37\\Scripts\\;C:\\Users\\user2\\AppData\\Local\\Programs\\Python\\Python37\\;C:\\Users\\user2\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\user2\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\GitHub CLI\\',
//              '_OLD_VIRTUAL_PROMPT': '$P$G', 
//              'DJANGO_SETTINGS_MODULE': 'config.settings',
//               'RUN_MAIN': 'true', 
//               'SERVER_NAME': 'kubernetes.docker.internal',
//              'GATEWAY_INTERFACE': 'CGI/1.1',
//               'SERVER_PORT': '8000', 
//               'REMOTE_HOST': '', 
//               'CONTENT_LENGTH': '',
//                'SCRIPT_NAME': '',
//                 'SERVER_PROTOCOL': 'HTTP/1.1', 
//                 'SERVER_SOFTWARE': 'WSGIServer/0.2',
//                  'REQUEST_METHOD': 'GET', 'PATH_INFO': '/productionline/productionlines/',
//                   'QUERY_STRING': '', 
//                   'REMOTE_ADDR': '127.0.0.1',
//                    'CONTENT_TYPE': 'text/plain', 
//                    'HTTP_HOST': '127.0.0.1:8000',
//                     'HTTP_CONNECTION': 'keep-alive', 
//                     'HTTP_SEC_CH_UA': '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
//                      'HTTP_AUTHORIZATION': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMyMzExMjI4LCJqdGkiOiJkZjhjZTQ0ZTk5NWM0OWE4ODBmZDhiZDRlZjUyMDA0NSIsInVzZXJfaWQiOjd9.NR4BaF9NmUVGPfWTZnHUih7LEjh0YCmuGV95TXVZJHc', 
//                      'HTTP_SEC_CH_UA_MOBILE': '?0', 
//                      'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36', 
//                      'HTTP_SEC_CH_UA_PLATFORM': '"Windows"', 
//                      'HTTP_ACCEPT': '*/*',
//                       'HTTP_ORIGIN': 'http://localhost:3000', 
//                       'HTTP_SEC_FETCH_SITE': 'cross-site', 
//                       'HTTP_SEC_FETCH_MODE': 'cors', 
//                       'HTTP_SEC_FETCH_DEST': 'empty',
//                        'HTTP_REFERER': 'http://localhost:3000/',
//                         'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
//                          'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
//                           'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x0000021DD1E99D08>, 
//                           'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
//                            'wsgi.version': (1, 0), 'wsgi.run_once': False,
//                             'wsgi.url_scheme': 'http', 
//                             'wsgi.multithread': True, 
//                             'wsgi.multiprocess': False, 
//                             'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}